"""Train and select the best theme classifier (TF-IDF + classical ML).

Theme labels used for training are automatically generated by keyword rules
(see create_theme_labels.py). They are NOT human-annotated ground truth.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import joblib
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

BACKEND_DIR = Path(__file__).resolve().parent.parent
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from app.config import (  # noqa: E402
    MAX_FEATURES,
    MODELS_DIR,
    NGRAM_RANGE,
    PROCESSED_DATA_DIR,
    RANDOM_STATE,
    TEST_SIZE,
    THEME_METRICS_PATH,
    THEME_MODEL_PATH,
    THEME_VECTORIZER_PATH,
)
from training.evaluate_models import evaluate_classifier, save_metrics  # noqa: E402


def build_candidates() -> dict:
    return {
        "LogisticRegression": LogisticRegression(
            max_iter=2000,
            class_weight="balanced",
            random_state=RANDOM_STATE,
            solver="lbfgs",
        ),
        "MultinomialNB": MultinomialNB(alpha=0.5),
        "LinearSVM": LinearSVC(
            class_weight="balanced",
            random_state=RANDOM_STATE,
            max_iter=5000,
            dual="auto",
        ),
    }


def train_theme(df: pd.DataFrame) -> dict:
    X = df["review_clean"].astype(str).values
    y = df["theme"].astype(str).values

    # Stratification needs >=2 samples per class; filter rare classes if needed
    counts = pd.Series(y).value_counts()
    rare = counts[counts < 2].index.tolist()
    if rare:
        print(f"Warning: merging rare theme classes (<2 samples) into Other: {rare}")
        y = pd.Series(y).replace({r: "Other" for r in rare}).values

    # Re-check after merge
    counts = pd.Series(y).value_counts()
    keep_mask = pd.Series(y).isin(counts[counts >= 2].index).values
    if not keep_mask.all():
        X = X[keep_mask]
        y = y[keep_mask]

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=TEST_SIZE,
        random_state=RANDOM_STATE,
        stratify=y,
    )

    # Fit TF-IDF ONLY on training data
    vectorizer = TfidfVectorizer(
        max_features=MAX_FEATURES,
        ngram_range=NGRAM_RANGE,
        min_df=1,
        sublinear_tf=True,
    )
    X_train_vec = vectorizer.fit_transform(X_train)
    X_test_vec = vectorizer.transform(X_test)

    results = {}
    best_name = None
    best_f1 = -1.0
    best_model = None
    labels = sorted(set(y))

    for name, model in build_candidates().items():
        print(f"Training theme model: {name} ...")
        model.fit(X_train_vec, y_train)
        y_pred = model.predict(X_test_vec)
        metrics = evaluate_classifier(y_test, y_pred, labels=labels)
        results[name] = metrics
        f1 = metrics["f1_weighted"]
        print(
            f"  {name}: accuracy={metrics['accuracy']:.4f} "
            f"f1_weighted={f1:.4f} f1_macro={metrics['f1_macro']:.4f}"
        )
        if f1 > best_f1:
            best_f1 = f1
            best_name = name
            best_model = model

    print(f"\nBest theme model: {best_name} (weighted F1={best_f1:.4f})")

    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(vectorizer, THEME_VECTORIZER_PATH)
    joblib.dump(best_model, THEME_MODEL_PATH)
    print(f"Saved: {THEME_VECTORIZER_PATH}")
    print(f"Saved: {THEME_MODEL_PATH}")

    summary = {
        "task": "theme",
        "label_source": (
            "Automatically generated keyword/rule-based labels "
            "(NOT human-annotated ground truth). Used to bootstrap the prototype."
        ),
        "best_model": best_name,
        "selection_metric": "f1_weighted",
        "selection_reason": (
            "Weighted F1 is preferred because theme classes are typically imbalanced; "
            "it balances precision/recall while accounting for class support."
        ),
        "test_size": TEST_SIZE,
        "random_state": RANDOM_STATE,
        "n_train": int(len(X_train)),
        "n_test": int(len(X_test)),
        "models": results,
        "best_metrics": results[best_name],
    }
    save_metrics(summary, THEME_METRICS_PATH)
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description="Train theme classifiers.")
    parser.add_argument(
        "--input",
        type=str,
        default=str(PROCESSED_DATA_DIR / "prepared_reviews.csv"),
    )
    args = parser.parse_args()

    path = Path(args.input)
    if not path.exists():
        print(f"Prepared data not found: {path}")
        print("Run: python -m training.prepare_data")
        sys.exit(1)

    df = pd.read_csv(path)
    if "review_clean" not in df.columns or "theme" not in df.columns:
        print("Prepared CSV must contain review_clean and theme columns.")
        sys.exit(1)

    print(f"Theme class counts:\n{df['theme'].value_counts().to_string()}")
    print(
        "\nNOTE: Theme labels are automatically generated and are NOT "
        "human-annotated ground truth.\n"
    )
    train_theme(df)


if __name__ == "__main__":
    main()
